import re

Isocitrate = 'MAASYSVPSMIMEEERRFEAEVAEVQAWWNTERFRLTKRAYSARDVVALRGTMRQSYASNELAQKLWRTL' \
          'KTHQANGTASRTFGALDPVQVTMMAKHLDTIYVSGWQCSSTHTSTNEPGPDLADYPYDTVPNKVEHLFFA' \
          'QQYHDRKQREARMSMSREERARTPFIDYLKPIIADGDTGFGGATATVKLCKLFVERGAAGVHIEDQSSVT' \
          'KKCGHMAGKVLVAVSEHINRLVAARLQFDVMGTETVLVARTDAVAATLIQTNVDTRDHQFILGASNPNLK' \
          'GKGLATLLSEAMAAGKTGPELQAIEDNWLGMAELKTFSQCVTDAIKKMNLAEYEKQRKLNEWMNHSSYEK' \
          'CLSHEQAREVAERLGLPNLFWDWDLPRTREGFYRFQGSVEAAIVRGWAFAEYCDLVWMETSSPDMVECTK' \
          'FSQGVKTLRPELMLAYNLSPSFNWDASGMNDNQMMDFIPRIAKLGYCWQFITLAGFHADALIVDTFAKDF' \
          'ARRGMLAYVEKIQREERSNGVDTLAHQKWSGANYYDRVLRTVQGGITSTAAMGKGVTEEQFEEKWTRTGA' \
          'TNLGDGSVVIAKARM'

FASTA_ID = 'NP_001233878.2'
PRISITE_ID = 'PS00161'


def finding_site(Isocitrate):
    x = re.search(r'KKCGHM', Isocitrate)
    return x.span()


print('Isocitrate lyase ({})  contains its active site ({}) starting from {}th position'.format(FASTA_ID, PRISITE_ID,
                                                                                                finding_site(Isocitrate)[
                                                                                                    0]))
